### PR TITLE
Rework masternode hierarchy

### PR DESCRIPTION
**Pull request by etienne-napoleone**
see #131

### CODE REVIEW

**Comment by etienne-napoleone** [comment]
Thanks @nyeates !
Just changed that!

**Comment by phamvancam2104** [comment]
@etienne-napoleone should `Running with` be changed to `Running a fullnode with` or `Running a masternode with`?

**Comment by etienne-napoleone** [comment]
In my opinion, as we're already in the "masternode" section, this is redundant. The other menu entries also doesn't contain this information

**Comment by phamvancam2104** [comment]
there is `Applying for Masternode Candidacy`: Running a masternode = running a fullnode + applying masternode candidacy for the fullnode. `Running with` does not mean that

**Comment by etienne-napoleone** [comment]
Yeah I see what you mean, but the goal is also not to over complicate it for the user.
Maybe just `Running a node with`. Fullnode will create confusion

**Pull request merged**
